nodeExporter:
  enabled: false
  
pushgateway:
  enabled: false
  
alertmanager:
  enabled: true
  useClusterRole: false

kubeStateMetrics:
  enabled: false

server:
  enabled: false
  useClusterRole: false