apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
    - git:
        repoURL: https://github.com/csouza-harness/appset-examples.git
        revision: master
        files:
        - path: "guestbook/env-config/**/config.json"
  template:
    metadata:
      name: 'guestbook-{{cluster_name}}'
    spec:
      project: 1b89578d
      source:
        repoURL: https://github.com/csouza-harness/appset-examples.git
        targetRevision: '{{target_revision}}'
        path: "guestbook/deployment"
        plugin:
          name: argocd-vault-plugin-kustomize
          env:
            - name: VAULT_ADDR
              value: https://sample-cluster-public-vault-78dcdf40.fc49adc5.z1.hashicorp.cloud:8200
            - name: VAULT_TOKEN
              value: hvs.CAESIFQn8cmwkguBjHh543HWlgC5hJ2UkKx6e-v8cOPvGOy9GigKImh2cy5Mb1dEekRTYUtBYnRKT2tjUXNwTmxIMkYuRDR6SUEQ4b8G
            - name: AVP_TYPE
              value: vault
            - name: AVP_AUTH_TYPE
              value: token
      destination:
        server: '{{cluster_address}}'
        namespace: guestbook
      syncPolicy:
        automated: {}
